### ISSUE TITLE
Times

### ISSUE THREAD

**Issue by msb002** [MHDLab/PostProcessor#8]
Cut time 1 and Cut time 2 are not in the same hour, is this a timezone issue or a format issue?

When adding cutting times and then loading them and trying to return to those markers, the 1 hour difference in cut time 2 doesn't work well with the plot.

![image](https://user-images.githubusercontent.com/22012762/50360055-9a22cc00-0513-11e9-898f-a2589c90a556.png)

![image](https://user-images.githubusercontent.com/22012762/50360077-aeff5f80-0513-11e9-8dac-6448478818fe.png)

**Comment by msb002** [comment]
Part two of this issue is actually in how we're reading the motor times.

![image](https://user-images.githubusercontent.com/22012762/50360499-1073fe00-0515-11e9-84e9-b147bda324e5.png)

![image](https://user-images.githubusercontent.com/22012762/50360532-22ee3780-0515-11e9-9dca-42bacf8fb359.png)

**Comment by aspitarl** [comment]
I set both inputs to 'local time' in Qt designer does that fix it?

**Comment by msb002** [comment]
Yes, I figured out the issue in the motor is that it's saving as a waveform so the postprocessor isnt looking for a time channel. I'll update the acquisition section.

**Comment by aspitarl** [comment]
Actually, layout.py was not correctly updated in the last commit. I'm not actually seeing the local time being set for the start time in layout.py...but test this out close the issue if there are no problems

**Comment by msb002** [comment]
Solution:

First: alicats and motors save numeric channels instead of waveforms

Second: postprocessor can now handle plotting numeric channels without specifying the time channel. It looks for the first channel in all groups with 'Time' in the channelname, double checks that its a datetime channel, and works with that. You can now get cutting times with even the powermeter (i'd recommend saving those in separate TDMS files unless there's some reason to not).
